#!/bin/sh
#
# Triggers the GitHub Actions workflow for deployments

curl -u gjtorikian:$GITHUB_TOKEN \
  -H "Accept: application/vnd.github.ant-man-preview+json" \
  -X POST \
  https://api.github.com/repos/BottleCapTechnology/gcp-gloud-functions-template/deployments \
  -d '{"ref": "production"}'
